<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📂 Práca so súbormi v dátovom spracovaní</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V tejto časti budeme pracovať s tromi bežnými formátmi, s ktorými sa môžete stretnúť pri dátovej analytike a pri tvorbe dátových pipeline:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li><strong>Excel (<span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">.xlsx</span>)</strong> – pohodlný formát pre manuálnu prácu a menšie datasety,</li>
<li><strong>CSV (<span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">.csv</span>)</strong> – jednoduchý textový formát vhodný na výmenu dát,</li>
<li><strong>Parquet (<span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">.parquet</span>)</strong> – stĺpcový binárny formát navrhnutý pre efektívne analytické spracovanie.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Cieľom nie je naučiť sa iba konkrétny príkaz na načítanie súboru. Dôležité je vedieť rozpoznať, aký typ súboru máme, ako ho načítať, ako skontrolovať jeho štruktúru a ako z neho vybrať iba tie dáta, ktoré skutočne potrebujeme.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Tieto kroky sa neskôr stanú súčasťou vašej vlastnej dátovej pipeline.</p>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 1. Excel súbory</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Excel je veľmi rozšírený pri manuálnej práci s dátami, reportingu a pri výmene menších datasetov medzi používateľmi.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na rozdiel od CSV môže jeden Excel súbor obsahovať viac listov, formátovanie, vzorce a ďalšie informácie. Pri analytickom spracovaní nás však zaujímajú predovšetkým samotné tabuľkové dáta.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pandas.read_excel()</span> načítame obsah listu do objektu <strong>DataFrame</strong>.</p>

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">1.1 Načítanie Excel súboru</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Po načítaní dát je dobrým zvykom najskôr zobraziť niekoľko prvých riadkov. Takto si overíme, že:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>sme otvorili správny súbor,</li>
<li>hlavička bola načítaná správne,</li>
<li>hodnoty vyzerajú podľa očakávania.</li>
</ul>
<div style="margin-top: 12px; background-color: #fefce8; border-left: 4px solid #eab308; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 Ak máte súbor uložený v rovnakom priečinku ako notebook, môžete použiť iba názov súboru namiesto celej cesty.</div>

In [1]:
import pandas as pd

df = pd.read_excel(r"sales_report.xlsx")
print(df.head(50))

FileNotFoundError: [Errno 2] No such file or directory: 'sales_report.xlsx'

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">1.2 Kontrola štruktúry datasetu</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Metóda <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">info()</span> nám ukáže počet riadkov, názvy stĺpcov, počet neprázdnych hodnôt a dátové typy.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Je to jedna z prvých kontrol, ktoré by sme mali vykonať pri každom neznámom datasete.</p>

In [ ]:
print("\nDataset Info:")
print(df.info())

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       100 non-null    int64
 1   Date          100 non-null    datetime64[ns]
 2   CustomerName  100 non-null    object
 3   Region        100 non-null    object
 4   Product       100 non-null    object
 5   Category      100 non-null    object
 6   Quantity      100 non-null    int64
 7   SalesAmount   100 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 6.4+ KB
None

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">1.3 Základný štatistický prehľad</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Metóda <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">describe()</span> poskytuje rýchly prehľad číselných stĺpcov napríklad počet hodnôt, priemer, minimum, maximum a kvartily.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Nejde ešte o samotnú analýzu. Je to skôr rýchla kontrola, či rozsahy hodnôt dávajú zmysel.</p>

In [ ]:
print("\nSummary Statistics:")
print(df.describe())

Summary Statistics:
           OrderID                 Date    Quantity  SalesAmount
count   100.000000                  100  100.000000   100.000000
mean   1050.500000  2023-02-19 12:00:00    4.690000  2717.300000
min    1001.000000  2023-01-01 00:00:00    1.000000   146.000000
25%    1025.750000  2023-01-25 18:00:00    2.000000   972.750000
50%    1050.500000  2023-02-19 12:00:00    4.500000  1950.000000
75%    1075.250000  2023-03-16 06:00:00    7.000000  4298.500000
max    1100.000000  2023-04-10 00:00:00    9.000000  8109.000000
std      29.011492                  NaN    2.642676  2118.615717

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">1.4 Filtrovanie riadkov</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">DataFrame môžeme filtrovať podľa podmienky podobne ako používame <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">WHERE</span> v SQL.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Nasledujúci príklad ponechá iba predaje z regiónu <strong>West</strong>.</p>

In [ ]:
west_sales = df[df["Region"] == "West"]
print(west_sales.head(10))

    OrderID       Date CustomerName Region  Product     Category  Quantity  \
1      1002 2023-01-02  Customer_29   West   Laptop  Electronics         8
2      1003 2023-01-03  Customer_15   West   Laptop  Electronics         4
3      1004 2023-01-04  Customer_43   West   Laptop  Electronics         6
8      1009 2023-01-09  Customer_23   West  Printer  Accessories         3
18     1019 2023-01-19  Customer_24   West    Phone  Electronics         4
21     1022 2023-01-22  Customer_38   West   Laptop  Electronics         4
22     1023 2023-01-23   Customer_2   West   Laptop  Electronics         8
25     1026 2023-01-26  Customer_12   West  Monitor  Accessories         3
29     1030 2023-01-30  Customer_49   West  Printer  Accessories         6
32     1033 2023-02-02  Customer_28   West    Phone  Electronics         6

    SalesAmount
1          6328
2          3124
3          5622
8          1089
18         1796
21         3688
22         7352
25         1407
29         4548
32         5580

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">1.5 Agregácia dát</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">groupby()</span> môžeme vytvárať agregácie podobne ako pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">GROUP BY</span> v SQL.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Tu vypočítame celkový predaj pre každý región.</p>

In [ ]:
region_sales = df.groupby("Region")["SalesAmount"].sum().reset_index()
print("\nTotal Sales by Region:")
print(region_sales)

Total Sales by Region:
  Region  SalesAmount
0   East        81147
1  North        55771
2  South        57228
3   West        77584

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">1.6 Uloženie výsledku</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Transformované alebo vyfiltrované dáta nemusíme ponechať iba v pamäti. Výsledok môžeme uložiť do nového súboru.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Parameter <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">index=False</span> zabezpečí, že pandas nepridá do Excelu vlastný číselný index ako ďalší stĺpec.</p>

In [ ]:
west_sales.to_excel("west_region_sales.xlsx", index=False)
print("Filtered data saved successfully!")

Filtered data saved successfully!

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 2. CSV – Comma-Separated Values</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">CSV je jednoduchý <strong>textový formát</strong>, v ktorom jeden riadok typicky predstavuje jeden záznam a jednotlivé hodnoty sú oddelené oddeľovačom.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Názov síce hovorí <em>Comma-Separated Values</em>, ale v praxi sa môžete stretnúť aj s inými oddeľovačmi, napríklad:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>čiarka <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">,</span>,</li>
<li>bodkočiarka <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">;</span>,</li>
<li>tabulátor.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri načítaní cudzieho CSV preto nie je dôležité iba vedieť, že ide o CSV. Potrebujeme poznať aj jeho <strong>delimiter, encoding, hlavičku a spôsob reprezentácie chýbajúcich hodnôt</strong>.</p>

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">2.1 Načítanie CSV</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;"><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">read_csv()</span> načíta textový súbor do DataFrame.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Aj tu si po načítaní najskôr zobrazíme niekoľko riadkov a následne skontrolujeme dátové typy.</p>

In [ ]:
import pandas as pd

df = pd.read_csv(r"employees.csv")
print(df.head(20))

    id              name  department  salary  gender  age   hire_date  \
0    1   William Stevens          IT    8867    Male   23  2024-06-13
1    2       Darryl Neal  Operations    9513  Female   27  2020-03-19
2    3    Benjamin Jones   Marketing   10461  Female   40  2017-10-29
3    4   Lisa Villarreal          HR   11161  Female   50  2017-07-09
4    5     Pamela Benton       Sales    9049  Female   40  2024-08-01
5    6    Jennifer Smith          IT   10723    Male   48  2016-04-08
6    7   Richard Baldwin          IT    8639  Female   40  2020-04-18
7    8    Richard Deleon   Marketing    9796    Male   50  2018-02-28
8    9    Sarah Williams          HR    4188  Female   27  2020-02-04
9   10  Alexis Suarez MD       Sales   11927    Male   52  2020-01-25
10  11    Jessica Monroe  Operations    7226  Female   50  2017-02-02
11  12    James Guerrero          IT    9461  Female   32  2025-01-03
12  13       Chloe Allen          IT    7033    Male   39  2017-04-23
13  14  Jeffrey Martinez          IT    6325    Male   48  2024-07-13
14  15      Janice Burns     Finance    6722    Male   58  2018-03-29
15  16        Randy Hays          HR    9749    Male   29  2016-04-11
16  17  Michael Perez MD          HR    7397    Male   33  2017-08-02
17  18    Deborah Harper     Finance   11982    Male   41  2016-06-19
18  19  Rebecca Williams  Operations    9719  Female   50  2023-03-22
19  20    Stephanie Hays       Sales    8336    Male   40  2016-04-20

                   city
0          Bautistaport
1           Melissatown
2           Jordanhaven
3            New Joshua
4   Lake Chelseaborough
5           South Jaime
6           Aliciaburgh
7             Smithview
8          New Samantha
9        Montgomeryberg
10            Perezstad
11            Lauraview
12   Port Dillonborough
13    South Brendanfort
14        South Tiffany
15            New Holly
16      North Juliebury
17       Salazarborough
18      Campbellchester
19         Kevinchester

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          100 non-null    int64
 1   name        100 non-null    object
 2   department  100 non-null    object
 3   salary      100 non-null    int64
 4   gender      100 non-null    object
 5   age         100 non-null    int64
 6   hire_date   100 non-null    object
 7   city        100 non-null    object
dtypes: int64(3), object(5)
memory usage: 6.4+ KB
None

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">2.2 Agregácie nad CSV dátami</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Po načítaní už pracujeme s DataFrame rovnako bez ohľadu na to, či zdrojom bol Excel alebo CSV.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Najskôr vypočítame priemernú mzdu podľa oddelenia.</p>

In [ ]:
avg_salary = df.groupby("department")["salary"].mean()
print("Average Salary by Department:")
print(avg_salary)

Average Salary by Department:
department
Finance       7302.800000
HR            8275.916667
IT            8562.043478
Marketing     7314.764706
Operations    8048.823529
Sales         7337.187500
Name: salary, dtype: float64

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Ďalším príkladom je počet zamestnancov podľa pohlavia. Metóda <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">value_counts()</span> spočíta výskyty jednotlivých hodnôt.</p>

In [ ]:
gender_count = df["gender"].value_counts()
print("Count by Gender:")
print(gender_count)

Count by Gender:
gender
Male      52
Female    48
Name: count, dtype: int64

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">2.3 Vytvorenie nových CSV súborov</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V praxi často nevytvárame iba jeden výsledok. Z jedného zdrojového datasetu môžeme pripraviť viac výstupov pre rôzne účely.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Nasledujúci príklad vytvorí:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>súbor zamestnancov z IT oddelenia,</li>
<li>súbor zamestnancov s platom vyšším ako 80 000.</li>
</ul>

In [ ]:
# Save IT employees to a new CSV
it_employees = df[df["department"] == "IT"]
it_employees.to_csv("it_employees.csv", index=False)

# Save high salary employees to CSV
high_salary = df[df["salary"] > 80000]
high_salary.to_csv("high_salary.csv", index=False)

print("Files created successfully: it_employees.csv and high_salary.csv")

Files created successfully: it_employees.csv and high_salary.csv

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 3. Apache Parquet</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Parquet je <strong>binárny stĺpcový formát</strong> navrhnutý pre efektívne ukladanie a analytické čítanie veľkých datasetov.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">CSV ukladá dáta po riadkoch. Parquet ich organizuje po stĺpcoch. To je výhodné najmä pri analytických úlohách, kde často potrebujeme pracovať iba s niekoľkými stĺpcami z veľmi širokej tabuľky.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Parquet navyše uchováva:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>dátové typy,</li>
<li>schému,</li>
<li>metadata,</li>
<li>štatistiky jednotlivých blokov,</li>
<li>kompresiu.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Preto je veľmi bežný v prostrediach ako Spark, Hadoop, dátové jazerá a cloudové analytické platformy.</p>

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Predstavte si dataset so 100 miliónmi riadkov a 80 stĺpcami.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Ak potrebujeme iba stĺpce <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">customer_id</span> a <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">sales</span>, pri CSV typicky čítame celý riadkový súbor. Pri Parquete môže engine načítať iba potrebné stĺpce.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Tento princíp sa nazýva <strong>column pruning</strong> a je jedným z dôvodov, prečo je Parquet vhodný pre analytické workloady.</p>

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.1 Potrebné knižnice</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;"><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pyarrow</span> je knižnica, ktorá umožňuje pandas čítať a zapisovať Parquet súbory.</p>
<div style="margin-top: 12px; background-color: #fefce8; border-left: 4px solid #eab308; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 V Jupyter notebooku je vhodnejšie používať %pip než klasický príkaz pip.</div>

In [2]:
%pip install pandas pyarrow fastparquet

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.13/dist-packages (23.0.1)
Collecting fastparquet
  Downloading fastparquet-2026.9.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (4.8 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.5)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.13/dist-packages (from fastparquet) (2.14.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.13/dist-packages (from fastparquet) (2025.12.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from fastparquet) (26.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading fastparquet-2026.9.0-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 13.5 MB/s  0:00:00
Installing collected packages: fastparquet
Successfully installed fastparquet-2026.9.0

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.2 Konverzia CSV do Parquet</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Tento príklad slúži na ukážku rozdielu medzi formátmi. CSV načítame do DataFrame a následne ho zapíšeme vo formáte Parquet.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V reálnej pipeline však môžeme dostať Parquet <strong>priamo zo zdrojového systému</strong> a žiadna konverzia z CSV nemusí prebehnúť.</p>

In [ ]:
import pandas as pd

df = pd.read_csv(r"sales_report+(1).csv")

df.to_parquet(
    "sales_report.parquet",
    engine="pyarrow",
    index=False
)

print("Sales dataset saved as Parquet")

Sales dataset saved as Parquet

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.3 Načítanie Parquet súboru</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na úrovni pandas je čítanie jednoduché <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">read_parquet()</span> vráti DataFrame.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Parquet však obsahuje viac informácií než iba samotné hodnoty. K schéme a metadátam sa dostaneme neskôr pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pyarrow</span>.</p>

In [ ]:
data = pd.read_parquet("sales_report.parquet", engine="pyarrow")

print("Dataset loaded from Parquet")
print(data.head(30))

Dataset loaded from Parquet
    OrderID        Date CustomerName Region  Product     Category  Quantity  \
0      1001  2023-01-01  Customer_39  North  Monitor  Accessories         1
1      1002  2023-01-02  Customer_29   West   Laptop  Electronics         8
2      1003  2023-01-03  Customer_15   West   Laptop  Electronics         4
3      1004  2023-01-04  Customer_43   West   Laptop  Electronics         6
4      1005  2023-01-05   Customer_8   East   Laptop  Electronics         8
5      1006  2023-01-06  Customer_21   East    Phone  Electronics         4
6      1007  2023-01-07  Customer_39   East   Laptop  Electronics         3
7      1008  2023-01-08  Customer_19  North  Monitor  Accessories         9
8      1009  2023-01-09  Customer_23   West  Printer  Accessories         3
9      1010  2023-01-10  Customer_11   East   Laptop  Electronics         9
10     1011  2023-01-11  Customer_11   East    Phone  Electronics         2
11     1012  2023-01-12  Customer_24  North    Phone  Electronics         2
12     1013  2023-01-13  Customer_36   East   Laptop  Electronics         2
13     1014  2023-01-14  Customer_40  North  Printer  Accessories         6
14     1015  2023-01-15  Customer_24  South   Laptop  Electronics         3
15     1016  2023-01-16   Customer_3   East    Phone  Electronics         9
16     1017  2023-01-17  Customer_22  South   Tablet  Electronics         4
17     1018  2023-01-18   Customer_2  North  Monitor  Accessories         1
18     1019  2023-01-19  Customer_24   West    Phone  Electronics         4
19     1020  2023-01-20  Customer_44   East   Laptop  Electronics         1
20     1021  2023-01-21  Customer_30  North  Monitor  Accessories         5
21     1022  2023-01-22  Customer_38   West   Laptop  Electronics         4
22     1023  2023-01-23   Customer_2   West   Laptop  Electronics         8
23     1024  2023-01-24  Customer_21  South   Tablet  Electronics         8
24     1025  2023-01-25  Customer_33  North  Monitor  Accessories         7
25     1026  2023-01-26  Customer_12   West  Monitor  Accessories         3
26     1027  2023-01-27  Customer_22   East   Tablet  Electronics         1
27     1028  2023-01-28  Customer_44   East    Phone  Electronics         1
28     1029  2023-01-29  Customer_25  South   Laptop  Electronics         3
29     1030  2023-01-30  Customer_49   West  Printer  Accessories         6

    SalesAmount
0           404
1          6328
2          3124
3          5622
4          7056
5           612
6          1629
7          6408
8          1089
9          1368
10         1342
11         1438
12          208
13         1212
14          885
15         7857
16         3904
17          983
18         1796
19          146
20         4830
21         3688
22         7352
23         6040
24         2576
25         1407
26          735
27          205
28         2307
29         4548

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.4 Načítanie iba vybraných stĺpcov</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri Parquete nemusíme načítať všetky stĺpce. Parameter <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">columns</span> umožní vybrať iba tie, ktoré potrebujeme.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Toto je dôležité pri veľkých datasetoch, znižujeme množstvo dát, ktoré musí engine prečítať.</p>

In [ ]:
df_small = pd.read_parquet(
    "sales_report.parquet",
    columns=["OrderID", "SalesAmount"]
)

print(df_small.head(10))

   OrderID  SalesAmount
0     1001          404
1     1002         6328
2     1003         3124
3     1004         5622
4     1005         7056
5     1006          612
6     1007         1629
7     1008         6408
8     1009         1089
9     1010         1368

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.5 Vytvorenie nového Parquet datasetu</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Nasledujúci blok vytvorí jednoduchý dataset a uloží ho do Parquet súboru. Cieľom je ukázať zápis dát a následné opätovné čítanie.</p>

In [ ]:
import pandas as pd
import numpy as np

data = {
    "OrderId": range(1, 101),
    "Product": np.random.choice(["Laptop", "Phone", "Tablet", "Monitor"], 100),
    "Category": np.random.choice(["Electronics", "Accessories"], 100),
    "Quantity": np.random.randint(1, 10, 100),
    "Price": np.random.randint(200, 2000, 100),
    "Region": np.random.choice(["North", "South", "East", "West"], 100),
    "Salesperson": np.random.choice(["Alice", "Bob", "Noah", "Diana"], 100)
}

df_new = pd.DataFrame(data)
df_new["SalesAmount"] = df_new["Quantity"] * df_new["Price"]

df_new.to_parquet("sales_report2.parquet", engine="pyarrow", index=False)

print("New Parquet dataset created.")

New Parquet dataset created.

In [ ]:
df_check = pd.read_parquet("sales_report2.parquet")
print(df_check.tail(10))

    OrderId  Product     Category  Quantity  Price Region Salesperson  \
90       91  Monitor  Electronics         1   1424  North       Alice
91       92   Tablet  Accessories         1   1981  North         Bob
92       93  Monitor  Accessories         3    284  North        Noah
93       94   Tablet  Electronics         8   1267   East       Diana
94       95   Laptop  Electronics         1    584   East       Diana
95       96  Monitor  Accessories         5    832   East         Bob
96       97    Phone  Accessories         8   1892   West        Noah
97       98  Monitor  Accessories         9   1262   East        Noah
98       99   Laptop  Electronics         2   1068  North         Bob
99      100   Tablet  Electronics         5    302   West        Noah

    SalesAmount
90         1424
91         1981
92          852
93        10136
94          584
95         4160
96        15136
97        11358
98         2136
99         1510

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.6 Pridanie ďalších dát</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Samotný Parquet súbor nie je databázová tabuľka, do ktorej jednoducho vykonáme <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">INSERT</span>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Jedna z možností je:</p>
<ol style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>existujúci súbor načítať,</li>
<li>vytvoriť nové riadky,</li>
<li>spojiť ich pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">concat()</span>,</li>
<li>výsledok znovu zapísať.</li>
</ol>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri veľkých dátových jazerách sa však zvyčajne pracuje s viacerými Parquet súbormi alebo s nadstavbovými tabuľkovými formátmi.</p>

In [ ]:
import pandas as pd
import numpy as np

df_old = pd.read_parquet("sales_report2.parquet")

new_data = {
    "OrderId": range(df_old["OrderId"].max() + 1, df_old["OrderId"].max() + 11),
    "Product": np.random.choice(["Laptop", "Phone", "Tablet", "Monitor"], 10),
    "Category": np.random.choice(["Electronics", "Accessories"], 10),
    "Quantity": np.random.randint(1, 10, 10),
    "Price": np.random.randint(200, 2000, 10),
    "Region": np.random.choice(["North", "South", "East", "West"], 10),
    "Salesperson": np.random.choice(["Alice", "Bob", "Noah", "Diana"], 10)
}

df_append = pd.DataFrame(new_data)
df_append["SalesAmount"] = df_append["Quantity"] * df_append["Price"]

df_combined = pd.concat([df_old, df_append], ignore_index=True)

df_combined.to_parquet("sales_report2.parquet", engine="pyarrow", index=False)

print("New rows added and Parquet file rewritten.")

New rows added and Parquet file rewritten.

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.7 Porovnanie veľkosti súborov</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Parquet používa kompresiu a stĺpcové uloženie, preto môže byť pri analytických dátach výrazne menší ako textové CSV.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Výsledok však závisí od konkrétnych dát, ako typov stĺpcov, opakovania hodnôt aj použitého kompresného algoritmu.</p>

In [ ]:
import os

csv_size = os.path.getsize(
    r"sales_report+(1).csv"
) / 1024 / 1024

pq_size = os.path.getsize(
    "sales_report.parquet"
) / 1024 / 1024

print(f"CSV size: {csv_size:.2f} MB")
print(f"Parquet size: {pq_size:.2f} MB")

CSV size: 0.01 MB
Parquet size: 0.01 MB

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">3.8 Partitioning</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri veľkých datasetoch môžeme dáta rozdeliť do fyzických adresárov podľa hodnoty vybraného stĺpca.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Ak partitionujeme podľa <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">Region</span>, vznikne štruktúra približne:</p>
<pre style="background: #f9fafb; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.55; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 12px 0 16px;">partitioned_sales/
├── Region=East/
├── Region=North/
├── Region=South/
└── Region=West/
</pre>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Ak neskôr potrebujeme iba <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">Region = West</span>, analytický engine môže preskočiť ostatné priečinky. Tento princíp sa nazýva <strong>partition pruning</strong>.</p>

In [ ]:
import pandas as pd
import os

df = pd.read_csv(r"sales_report+(1).csv")

df["Date"] = pd.to_datetime(df["Date"])

output_dir = r"partitioned_sales"
os.makedirs(output_dir, exist_ok=True)

df.to_parquet(
    output_dir,
    engine="pyarrow",
    partition_cols=["Region"],
    index=False,
    coerce_timestamps="us",
    allow_truncated_timestamps=True
)

print("Partitioned Parquet dataset saved.")

Partitioned Parquet dataset saved.

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4. Práca s reálnym Parquet súborom – NYC Yellow Taxi</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V tejto časti už nebudeme Parquet iba vytvárať z CSV. Budeme pracovať so súborom, ktorý bol publikovaný priamo vo formáte <strong>Parquet</strong>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Použijeme dáta <strong>NYC Yellow Taxi Trip Records – January 2024</strong>. Každý riadok predstavuje jednu jazdu taxíkom a medzi stĺpcami nájdeme napríklad:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">tpep_pickup_datetime</span> – čas začiatku jazdy,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">tpep_dropoff_datetime</span> – čas ukončenia jazdy,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">passenger_count</span> – počet cestujúcich,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">trip_distance</span> – prejdenú vzdialenosť,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">PULocationID</span> a <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">DOLocationID</span> – identifikátory nástupnej a výstupnej zóny,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">fare_amount</span> – základnú cenu jazdy,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">tip_amount</span> – prepitné,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">total_amount</span> – celkovú zaplatenú sumu.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na tomto súbore si ukážeme, čo všetko môžeme zistiť ešte <strong>pred načítaním celého datasetu do pandas</strong>.</p>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.1 Stiahnutie Parquet súboru</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Najskôr si stiahneme januárové Yellow Taxi dáta.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Dôležité je, že tento súbor už prichádza ako <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">.parquet</span>. Nevykonávame teda konverziu z CSV. Budeme pracovať so súborom v takom formáte, v akom ho poskytuje zdroj.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Kód nižšie súbor stiahne iba vtedy, ak ešte nie je uložený v priečinku notebooku.</p>

In [ ]:
from urllib.request import urlretrieve
from pathlib import Path

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2024-01.parquet"
file_path = Path("yellow_tripdata_2024-01.parquet")

if not file_path.exists():
    urlretrieve(url, file_path)
    print("Parquet file downloaded.")
else:
    print("Parquet file already exists.")

print(file_path)

Parquet file already exists.
yellow_tripdata_2024-01.parquet

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.2 Otvorenie Parquet súboru pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">ParquetFile</span></h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Bežný prístup by bol:</p>
<pre style="background: #f9fafb; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.55; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 12px 0 16px;">pd.read_parquet(...)
</pre>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Tým by sme však hneď začali načítavať dáta do DataFrame.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Teraz chceme najprv zistiť, <strong>čo je vo vnútri súboru</strong>, preto použijeme:</p>
<pre style="background: #f9fafb; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.55; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 12px 0 16px;">pq.ParquetFile(...)
</pre>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Výsledkom nebude pandas DataFrame, ale objekt reprezentujúci samotný Parquet súbor. Z neho vieme čítať schému, metadata a informácie o row groups.</p>

In [ ]:
import pyarrow.parquet as pq

parquet_file = pq.ParquetFile("yellow_tripdata_2024-01.parquet")

print(type(parquet_file))

<class 'pyarrow.parquet.core.ParquetFile'>

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">Čo je objekt <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">ParquetFile</span>?</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Premenná <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">parquet_file</span> ešte neobsahuje tabuľku jázd tak, ako ju poznáme z pandas.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Predstavuje súbor a jeho štruktúru. Cez tento objekt vieme napríklad zistiť:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>aké stĺpce sú v súbore,</li>
<li>aké majú dátové typy,</li>
<li>koľko riadkov súbor obsahuje,</li>
<li>na koľko row groups je rozdelený,</li>
<li>aké metadata sú uložené pri jednotlivých stĺpcoch.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Takto vieme súbor najskôr preskúmať a až potom sa rozhodnúť, čo z neho chceme načítať.</p>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.3 Schéma – aké stĺpce a typy obsahujú taxi dáta</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Parquet si uchováva dátové typy priamo v súbore. Preto už zo schémy vieme rozlíšiť napríklad:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>identifikátory ako celé čísla,</li>
<li><span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">trip_distance</span>, <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">fare_amount</span> alebo <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">total_amount</span> ako číselné hodnoty,</li>
<li>pickup a dropoff časy ako timestampy.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri CSV by sme sa pri načítaní museli spoliehať na to, že pandas dátové typy správne odhadne.</p>

In [ ]:
print(parquet_file.schema)

<pyarrow._parquet.ParquetSchema object at 0x000001DE9BA919C0>
required group field_id=-1 schema {
  optional int32 field_id=-1 VendorID;
  optional int64 field_id=-1 tpep_pickup_datetime (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional int64 field_id=-1 tpep_dropoff_datetime (Timestamp(isAdjustedToUTC=false, timeUnit=microseconds, is_from_converted_type=false, force_set_converted_type=false));
  optional int64 field_id=-1 passenger_count;
  optional double field_id=-1 trip_distance;
  optional int64 field_id=-1 RatecodeID;
  optional binary field_id=-1 store_and_fwd_flag (String);
  optional int32 field_id=-1 PULocationID;
  optional int32 field_id=-1 DOLocationID;
  optional int64 field_id=-1 payment_type;
  optional double field_id=-1 fare_amount;
  optional double field_id=-1 extra;
  optional double field_id=-1 mta_tax;
  optional double field_id=-1 tip_amount;
  optional double field_id=-1 tolls_amount;
  optional double field_id=-1 improvement_surcharge;
  optional double field_id=-1 total_amount;
  optional double field_id=-1 congestion_surcharge;
  optional double field_id=-1 Airport_fee;
}

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Schému môžeme zobraziť aj vo forme Arrow schémy, ktorá je pri programovej práci o niečo prehľadnejšia.</p>

In [ ]:
print(parquet_file.schema_arrow)

VendorID: int32
tpep_pickup_datetime: timestamp[us]
tpep_dropoff_datetime: timestamp[us]
passenger_count: int64
trip_distance: double
RatecodeID: int64
store_and_fwd_flag: large_string
PULocationID: int32
DOLocationID: int32
payment_type: int64
fare_amount: double
extra: double
mta_tax: double
tip_amount: double
tolls_amount: double
improvement_surcharge: double
total_amount: double
congestion_surcharge: double
Airport_fee: double

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.4 Koľko dát je v súbore?</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Teraz si pozrieme metadata celého januárového súboru.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Zaujíma nás najmä:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>koľko taxi jázd súbor obsahuje,</li>
<li>koľko má stĺpcov,</li>
<li>na koľko row groups je rozdelený,</li>
<li>akým nástrojom bol Parquet súbor vytvorený.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Toto všetko vieme zistiť bez toho, aby sme načítali milióny riadkov do pandas.</p>

In [ ]:
metadata = parquet_file.metadata

print("Number of rows:", metadata.num_rows)
print("Number of columns:", metadata.num_columns)
print("Number of row groups:", metadata.num_row_groups)
print("Created by:", metadata.created_by)

Number of rows: 2964624
Number of columns: 19
Number of row groups: 3
Created by: parquet-cpp-arrow version 14.0.2

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">Čo je row group v tomto taxi datasete?</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Parquet nerozdeľuje januárové taxi dáta iba podľa stĺpcov. Riadky sú zároveň rozdelené do väčších blokov <strong>row groups</strong>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Každý row group obsahuje časť jázd a vo vnútri sú jeho stĺpce uložené samostatne.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Napríklad jeden row group obsahuje svoju časť:</p>
<pre style="background: #f9fafb; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.55; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 12px 0 16px;">trip_distance
fare_amount
tip_amount
total_amount
...
</pre>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">a ďalší row group obsahuje ďalšiu časť jázd.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Vďaka tomu nemusí analytický nástroj vždy čítať celý súbor naraz.</p>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.5 Ako vyzerá jeden row group</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pozrime sa na prvý row group.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Nečítame ešte konkrétne jazdy. Zisťujeme iba technické informácie:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>koľko riadkov obsahuje,</li>
<li>koľko má stĺpcov,</li>
<li>akú veľkosť predstavuje.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Potom rovnaké údaje vypíšeme pre všetky row groups a uvidíme, ako je januárový dataset rozdelený.</p>

In [ ]:
row_group = metadata.row_group(0)

print("Rows:", row_group.num_rows)
print("Columns:", row_group.num_columns)
print("Total byte size:", row_group.total_byte_size)

Rows: 1048576
Columns: 19
Total byte size: 28237137

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Teraz si môžeme porovnať všetky row groups v súbore.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Takýto prehľad nám ukáže, ako je dataset fyzicky rozdelený.</p>

In [ ]:
for i in range(metadata.num_row_groups):
    rg = metadata.row_group(i)
    print(
        f"Row group {i}: "
        f"rows={rg.num_rows:,}, "
        f"columns={rg.num_columns}, "
        f"size={rg.total_byte_size / 1024 / 1024:.2f} MB"
    )

Row group 0: rows=1,048,576, columns=19, size=26.93 MB
Row group 1: rows=1,048,576, columns=19, size=26.66 MB
Row group 2: rows=867,472, columns=19, size=21.60 MB

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V rámci jedného row group môžeme ísť ešte hlbšie a pozrieť sa na konkrétny stĺpec.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri column chunk nás nezaujímajú jednotlivé hodnoty jázd, ale napríklad:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>fyzický dátový typ,</li>
<li>použitá kompresia,</li>
<li>počet uložených hodnôt,</li>
<li>komprimovaná a nekomprimovaná veľkosť.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Takto vieme vidieť, ako Parquet fyzicky ukladá jednotlivé stĺpce.</p>

In [ ]:
column = metadata.row_group(0).column(0)

print("Column:", column.path_in_schema)
print("Physical type:", column.physical_type)
print("Compression:", column.compression)
print("Number of values:", column.num_values)
print("Compressed size:", column.total_compressed_size)
print("Uncompressed size:", column.total_uncompressed_size)

Column: VendorID
Physical type: INT32
Compression: ZSTD
Number of values: 1048576
Compressed size: 120829
Uncompressed size: 158152

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.6 Minimum, maximum a NULL hodnoty bez načítania stĺpca</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri niektorých stĺpcoch Parquet ukladá aj štatistiky.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na stĺpci <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">trip_distance</span> si vieme pozrieť napríklad:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>minimálnu vzdialenosť,</li>
<li>maximálnu vzdialenosť,</li>
<li>počet <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">NULL</span> hodnôt.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Dôležité je, že tieto hodnoty čítame z metadát. Nepočítame ich teraz z celého stĺpca pomocou pandas.</p>

In [ ]:
stats = column.statistics

print(stats)

None

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri číselnom stĺpci sú minimum a maximum zaujímavejšie. Nájdime si napríklad <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">trip_distance</span>.</p>

In [ ]:
column_names = parquet_file.schema_arrow.names
trip_distance_index = column_names.index("trip_distance")

trip_column = metadata.row_group(0).column(trip_distance_index)
stats = trip_column.statistics

print("Column:", trip_column.path_in_schema)
print("Compression:", trip_column.compression)

if stats is not None:
    print("Min:", stats.min)
    print("Max:", stats.max)
    print("Null count:", stats.null_count)
else:
    print("Statistics are not available.")

Column: trip_distance
Compression: ZSTD
Statistics are not available.

<h3 style="margin: 20px 0 10px; font-size: 17px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827;">Prečo sú tieto štatistiky užitočné?</h3>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Predstavte si, že hľadáme iba veľmi dlhé jazdy, napríklad:</p>
<pre style="background: #f9fafb; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.55; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 12px 0 16px;">trip_distance &gt; 100
</pre>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Ak má niektorý row group v metadátach uvedené:</p>
<pre style="background: #f9fafb; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.55; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; margin: 12px 0 16px;">min = 0.0
max = 18.7
</pre>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">je zrejmé, že v tomto bloku sa žiadna jazda nad 100 nenachádza.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Analytický engine preto môže taký row group preskočiť. Nemusí čítať jeho hodnoty len preto, aby následne zistil, že podmienku nič nespĺňa.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Toto je jeden z praktických dôvodov, prečo je Parquet efektívny pri filtrovaní veľkých analytických datasetov.</p>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.7 Načítanie iba časti taxi dát</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Doteraz sme čítali iba metadata. Teraz si načítame prvý row group, ale stále nie celý súbor.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Vyberieme si iba štyri stĺpce:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>čas nástupu,</li>
<li>vzdialenosť jazdy,</li>
<li>základnú cenu,</li>
<li>celkovú zaplatenú sumu.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Výsledkom bude objekt <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pyarrow.Table</span>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Až následne ho skonvertujeme do pandas DataFrame.</p>

In [ ]:
table = parquet_file.read_row_group(
    0,
    columns=[
        "tpep_pickup_datetime",
        "trip_distance",
        "fare_amount",
        "total_amount"
    ]
)

print(type(table))
print(table.schema)

<class 'pyarrow.lib.Table'>
tpep_pickup_datetime: timestamp[us]
trip_distance: double
fare_amount: double
total_amount: double

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Objekt, ktorý sme získali, je <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pyarrow.Table</span>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Až keď potrebujeme pracovať s dátami spôsobom, ktorý poznáme z pandas, môžeme ho skonvertovať do DataFrame.</p>

In [ ]:
df_row_group = table.to_pandas()

print(type(df_row_group))
print(df_row_group.head(10))

<class 'pandas.core.frame.DataFrame'>
  tpep_pickup_datetime  trip_distance  fare_amount  total_amount
0  2024-01-01 00:57:55           1.72         17.7         22.70
1  2024-01-01 00:03:00           1.80         10.0         18.75
2  2024-01-01 00:17:06           4.70         23.3         31.30
3  2024-01-01 00:36:38           1.40         10.0         17.00
4  2024-01-01 00:46:51           0.80          7.9         16.10
5  2024-01-01 00:54:08           4.70         29.6         41.50
6  2024-01-01 00:49:44          10.82         45.7         64.95
7  2024-01-01 00:30:40           3.00         25.4         30.40
8  2024-01-01 00:26:01           5.44         31.0         36.00
9  2024-01-01 00:28:08           0.04          3.0          8.00

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.8 Načítanie iba stĺpcov, ktoré potrebujeme</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Predstavme si, že chceme analyzovať iba vzťah medzi:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>časom jazdy,</li>
<li>prejdenou vzdialenosťou,</li>
<li>cenou jazdy,</li>
<li>celkovou zaplatenou sumou.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na takúto úlohu nepotrebujeme načítať napríklad <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">VendorID</span>, <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">RatecodeID</span>, <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">PULocationID</span> ani ďalšie stĺpce.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Preto pri <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">read_parquet()</span> uvedieme iba stĺpce, s ktorými budeme reálne pracovať.</p>

In [ ]:
import pandas as pd

df_small = pd.read_parquet(
    "yellow_tripdata_2024-01.parquet",
    columns=[
        "tpep_pickup_datetime",
        "trip_distance",
        "fare_amount",
        "total_amount"
    ]
)

print(df_small.head())
print(df_small.info())

  tpep_pickup_datetime  trip_distance  fare_amount  total_amount
0  2024-01-01 00:57:55           1.72         17.7         22.70
1  2024-01-01 00:03:00           1.80         10.0         18.75
2  2024-01-01 00:17:06           4.70         23.3         31.30
3  2024-01-01 00:36:38           1.40         10.0         17.00
4  2024-01-01 00:46:51           0.80          7.9         16.10
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2964624 entries, 0 to 2964623
Data columns (total 4 columns):
 #   Column                Dtype
---  ------                -----
 0   tpep_pickup_datetime  datetime64[us]
 1   trip_distance         float64
 2   fare_amount           float64
 3   total_amount          float64
dtypes: datetime64[us](1), float64(3)
memory usage: 90.5 MB
None

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Toto je praktická ukážka princípu <strong>column pruning</strong>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri veľmi širokých datasetoch môže byť rozdiel medzi načítaním 4 a 80 stĺpcov výrazný z pohľadu:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>množstva načítaných dát,</li>
<li>pamäte,</li>
<li>času spracovania.</li>
</ul>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 4.9 Prvá jednoduchá otázka nad dátami</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Keď už poznáme schému a vieme načítať iba potrebné stĺpce, môžeme začať pracovať s hodnotami.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Ako prvú kontrolu si vypočítame:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>priemernú vzdialenosť jazdy,</li>
<li>priemernú základnú cenu,</li>
<li>priemernú celkovú zaplatenú sumu.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Toto už je klasická analytická operácia v pandas. Rozdiel je v tom, že pred ňou sme si najskôr overili štruktúru súboru a načítali iba relevantné stĺpce.</p>

In [ ]:
summary = df_small[[
    "trip_distance",
    "fare_amount",
    "total_amount"
]].mean()

print(summary)

trip_distance     3.652169
fare_amount      18.175062
total_amount     26.801505
dtype: float64

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">5. Samostatná úloha – NYC Green Taxi</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">V tejto časti budete pracovať s datasetom <strong>Green Taxi Trip Records – January 2024</strong>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Postupujte podobne ako pri Yellow Taxi datasete, ale riešenie neprispôsobujte podľa predchádzajúcich názvov stĺpcov. Najskôr si sami preskúmajte schému súboru a až potom pokračujte v ďalších krokoch.</p>

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">📘 5.1 Stiahnite pridelený Parquet súbor</h2>

In [ ]:
# Vaše riešenie

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 1 – Základná identifikácia súboru</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pyarrow.parquet.ParquetFile</span> otvorte pridelený Parquet súbor <strong>bez toho, aby ste ho najskôr načítali do pandas</strong>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Zistite a vypíšte:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>počet riadkov,</li>
<li>počet stĺpcov,</li>
<li>počet row groups,</li>
<li>schému súboru,</li>
<li>hodnotu <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">created_by</span>.</li>
</ul>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 <strong>Zamyslite sa:</strong> Ktoré stĺpce sú číselné, ktoré časové a ktoré by ste podľa názvu považovali za identifikačné alebo kategorické?</div>

In [3]:
import pyarrow.parquet as pq

parquet_file = pq.ParquetFile('green_tripdata_2024-01.parquet')
metadata = parquet_file.metadata

print(metadata.num_rows)
print(metadata.num_columns)
print(metadata.num_row_groups)
print(metadata.created_by)

print(parquet_file.schema_arrow)

56551
20
1
parquet-cpp-arrow version 14.0.2
VendorID: int32
lpep_pickup_datetime: timestamp[us]
lpep_dropoff_datetime: timestamp[us]
store_and_fwd_flag: large_string
RatecodeID: int64
PULocationID: int32
DOLocationID: int32
passenger_count: int64
trip_distance: double
fare_amount: double
extra: double
mta_tax: double
tip_amount: double
tolls_amount: double
ehail_fee: double
improvement_surcharge: double
total_amount: double
payment_type: int64
trip_type: int64
congestion_surcharge: double

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 2 – Preskúmanie row groups</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pre každý row group zistite:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>jeho index,</li>
<li>počet riadkov,</li>
<li>počet stĺpcov,</li>
<li>približnú veľkosť v MB.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Výsledok zobrazte prehľadne.</p>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 <strong>Zamyslite sa:</strong> Majú všetky row groups rovnaký počet riadkov? Je posledný row group menší než ostatné? Prečo to tak môže byť?</div>

In [5]:
for i in range(metadata.num_row_groups):
    rg = metadata.row_group(i)
    print(
        f"Row group {i}: "
        f"riadky={rg.num_rows:,}, "
        f"stlpce={rg.num_columns}, "
        f"velkost={rg.total_byte_size / 1024 / 1024:.2f} MB"
    )

Row group 0: riadky=56,551, stlpce=20, velkost=1.68 MB

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 3 – Metadata vybraného stĺpca</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Zo schémy si vyberte jeden vhodný <strong>číselný stĺpec</strong> a preskúmajte jeho metadata v prvom row group.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Zistite:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>názov stĺpca,</li>
<li>fyzický dátový typ,</li>
<li>použitú kompresiu,</li>
<li>počet hodnôt,</li>
<li>komprimovanú veľkosť,</li>
<li>nekomprimovanú veľkosť,</li>
<li>minimum,</li>
<li>maximum,</li>
<li>počet <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">NULL</span> hodnôt.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Ak niektorá zo štatistík nie je dostupná, ošetrite túto situáciu v kóde.</p>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 <strong>Zamyslite sa:</strong> Čo vám minimum a maximum hovoria o hodnotách uložených v tomto row group?</div>

In [7]:
column_name = "trip_distance"
column_names = parquet_file.schema_arrow.names
col_index = column_names.index(column_name)

col_meta = metadata.row_group(0).column(col_index)
stats = col_meta.statistics

print("nazov stlpca:", col_meta.path_in_schema)
print("fyzicky datovy typ:", col_meta.physical_type)
print("pouzita kompresia:", col_meta.compression)
print("pocet hodnot:", col_meta.num_values)
print(f"komprimovana velkost: {col_meta.total_compressed_size / 1024:.2f} KB")
print(f"nekomprimovana velkost: {col_meta.total_uncompressed_size / 1024:.2f} KB")

if stats is not None:
    print("min:", stats.min if stats.has_min_max else "nedostupne")
    print("max:", stats.max if stats.has_min_max else "nedostupne")
    print("pocet null:", stats.null_count if stats.has_null_count else "nedotsupne")
else:
    print("min: nedostupne")
    print("max: nedostupne")
    print("pocet null: nedostupne")

nazov stlpca: trip_distance
fyzicky datovy typ: DOUBLE
pouzita kompresia: ZSTD
pocet hodnot: 56551
komprimovana velkost: 79.14 KB
nekomprimovana velkost: 90.86 KB
min: nedostupne
max: nedostupne
pocet null: nedostupne

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 4 – Načítanie iba vybraných stĺpcov</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Zo schémy si vyberte:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>jeden časový stĺpec,</li>
<li>jeden identifikačný alebo kategorický stĺpec,</li>
<li>dva číselné stĺpce.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pd.read_parquet(..., columns=[...])</span> načítajte <strong>iba tieto štyri stĺpce</strong>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Následne:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>zobrazte prvých 10 riadkov,</li>
<li>zobrazte dátové typy,</li>
<li>zistite počet chýbajúcich hodnôt,</li>
<li>zobrazte základné štatistiky číselných stĺpcov.</li>
</ul>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 <strong>Zamyslite sa:</strong> Prečo je pri veľkom Parquet súbore výhodné načítať iba stĺpce, ktoré skutočne potrebujeme?</div>

In [8]:
import pandas as pd

selected_columns = [
    "lpep_pickup_datetime",
    "PULocationID",
    "trip_distance",
    "total_amount"
]

df_selected = pd.read_parquet("green_tripdata_2024-01.parquet", columns=selected_columns)

display(df_selected.head(10))

print(df_selected.dtypes)

print(df_selected.isnull().sum())

display(df_selected[["trip_distance", "total_amount"]].describe())

  lpep_pickup_datetime  PULocationID  trip_distance  total_amount
0  2024-01-01 00:46:55           236           1.98         21.66
1  2024-01-01 00:31:42            65           6.54         42.66
2  2024-01-01 00:30:21            74           3.08         28.05
3  2024-01-01 00:30:20            74           2.40         16.70
4  2024-01-01 00:32:38            74           5.14         31.38
5  2024-01-01 00:43:41            33           2.00         24.25
6  2024-01-01 00:31:56            74           3.20         28.35
7  2024-01-01 00:46:12           166           2.01         24.37
8  2024-01-01 00:38:07           226           0.31          6.20
9  2024-01-01 00:44:24             7           2.32         20.88

lpep_pickup_datetime    datetime64[us]
PULocationID                     int32
trip_distance                  float64
total_amount                   float64
dtype: object
lpep_pickup_datetime    0
PULocationID            0
trip_distance           0
total_amount            0
dtype: int64

       trip_distance  total_amount
count   56551.000000  56551.000000
mean       31.491124     22.403186
std      1417.460382     16.956518
min         0.000000    -76.500000
25%         1.100000     13.440000
50%         1.790000     18.420000
75%         3.080000     26.600000
max    201421.680000   1424.100000

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 5 – Načítanie jedného row group</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pomocou <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">read_row_group()</span> načítajte iba <strong>prvý row group</strong> a iba stĺpce, ktoré ste použili v predchádzajúcej úlohe.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Zistite:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>aký typ objektu metóda vrátila,</li>
<li>koľko riadkov obsahuje,</li>
<li>akú má schému.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Následne ho skonvertujte na pandas DataFrame a zobrazte prvých 5 riadkov.</p>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 <strong>Zamyslite sa:</strong> Aký je rozdiel medzi objektom, ktorý vráti `read_row_group()`, a objektom `pandas.DataFrame`?</div>

In [9]:
table_rg = parquet_file.read_row_group(
    0,
    columns=selected_columns
)

print("typ:", type(table_rg))
print("pocet riadkov:", table_rg.num_rows)
print("schema:")
print(table_rg.schema)

df_rg = table_rg.to_pandas()
display(df_rg.head(5))

typ: <class 'pyarrow.lib.Table'>
pocet riadkov: 56551
schema:
lpep_pickup_datetime: timestamp[us]
PULocationID: int32
trip_distance: double
total_amount: double

  lpep_pickup_datetime  PULocationID  trip_distance  total_amount
0  2024-01-01 00:46:55           236           1.98         21.66
1  2024-01-01 00:31:42            65           6.54         42.66
2  2024-01-01 00:30:21            74           3.08         28.05
3  2024-01-01 00:30:20            74           2.40         16.70
4  2024-01-01 00:32:38            74           5.14         31.38

<h2 style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">💻 Úloha 6 – Vlastná analytická otázka</h2>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Na základe stĺpcov v Green Taxi datasete vytvorte <strong>jednu zmysluplnú analytickú otázku</strong>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Môžete sa zamerať napríklad na:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>cenu jazdy,</li>
<li>vzdialenosť,</li>
<li>spôsob platby,</li>
<li>počet jázd,</li>
<li>čas začiatku jazdy,</li>
<li>inú vhodnú vlastnosť podľa dostupných stĺpcov.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Postup:</p>
<ol style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>formulujte otázku jednou vetou,</li>
<li>načítajte iba stĺpce, ktoré na jej zodpovedanie potrebujete,</li>
<li>vykonajte potrebnú transformáciu alebo agregáciu,</li>
<li>zobrazte výsledok,</li>
<li>výsledok interpretujte jednou až dvoma vetami.</li>
</ol>
<div style="margin-top: 12px; background-color: #f9fafb; border-left: 4px solid #60a5fa; padding: 12px; border-radius: 4px; font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.6;">💡 <strong>Zamyslite sa:</strong> Keby bol tento súbor súčasťou ETL pipeline, ktoré z krokov, ktoré ste práve vykonali, by ste chceli automatizovať?</div>

In [ ]:
#otazka: Aka je priemerná celková suma (total_amount) a priemerná vzdialenosť jazdy (trip_distance) pre jednotlivé typy platieb (payment_type)?

analysis_cols = ["payment_type", "trip_distance", "total_amount"]
df_analysis = pd.read_parquet("green_tripdata_2024-01.parquet", columns=analysis_cols)

payment_stats = df_analysis.groupby("payment_type").agg(
    priemerna_vzdialenost=("trip_distance", "mean"),
    priemerna_cena=("total_amount", "mean"),
    pocet_jazd=("payment_type", "count")
).reset_index()

display(payment_stats)

# Z vysledkov mozme vidiet, ze typ platby má vplyv na priemernú dlzku a cenu jazdy.
# Cestujuci, ktori jazdia na dlhsie vzdialenosti a platia vyssie sumy, castejsie vyuzivaju bezhotovostne platby.

<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Po tejto časti by ste nemali Parquet vnímať iba ako súbor, ktorý otvoríme cez <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">pd.read_parquet()</span>.</p>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Mali by ste vedieť:</p>
<ul style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.7; margin-top: 6px;">
<li>pozrieť si jeho schému ešte pred načítaním dát,</li>
<li>zistiť počet riadkov a row groups,</li>
<li>pristúpiť k metadátam konkrétneho row group,</li>
<li>pozrieť si metadata konkrétneho stĺpca,</li>
<li>zistiť minimum, maximum a počet <span style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">NULL</span> hodnôt, ak sú štatistiky dostupné,</li>
<li>načítať iba jeden row group,</li>
<li>načítať iba vybrané stĺpce.</li>
</ul>
<p style="font-family: 'Segoe UI', Roboto, sans-serif; color: #1f2937; line-height: 1.65; margin: 8px 0 12px;">Pri väčšom Parquet súbore je často zbytočné začínať načítaním všetkých stĺpcov a všetkých riadkov. Najskôr si treba zistiť, čo súbor obsahuje a čo z neho pre danú úlohu skutočne potrebujeme.</p>

<h2
  style="margin: 24px 0 16px; font-size: 20px; font-weight: 600; font-family: 'Segoe UI', Roboto, sans-serif; color: #111827; border-bottom: 2px solid #e5e7eb; padding-bottom: 6px;">
  📘 Kontrola Git repozitára po 5. týždni</h2>

<p>Po dokončení všetkých úloh z 5. týždňa skontrolujte, či máte vo svojom Git
  repozitári vytvorenú samostatnú vetvu, napr. <span
    style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">week-05</span>,
  a či sa v nej nachádza vypracovaný notebook spolu so súbormi vytvorenými počas cvičenia.</p>

<p>Obsah vetvy <span
    style="background-color: #f2f2f2; font-family: monospace; padding: 2px 4px; border-radius: 3px;">week-05</span>
  by mal mať približne nasledujúcu štruktúru:</p>

<pre
  style="background: #f9fafb; padding: 16px; border-radius: 8px; overflow: auto; font-size: 14px; line-height: 1.7; font-family: ui-monospace, SFMono-Regular, Menlo, monospace;">week-05
│
├── file_handling.ipynb
├── high_salary.csv
├── it_employees.csv
├── sales_report.parquet
├── sales_report2.parquet
├── west_region_sales.xlsx
└── yellow_tripdata_2024-01.parquet</pre>

<p>V repozitári ponechajte nielen samotný notebook, ale aj výstupné súbory,
  ktoré ste počas jeho riešenia vytvorili. Vďaka tomu bude možné neskôr
  skontrolovať výsledky jednotlivých transformácií a znovu nadviazať na ďalšie
  kroky spracovania dát.</p>

<div
  style="margin-top: 12px; background-color: #fff7ed; border-left: 4px solid #f59e0b; padding: 12px; border-radius: 4px;">
  ⚠️ <strong>Kontrola GitHubu:</strong> Skontrolujte, či sa všetky uvedené súbory
  nachádzajú aj vo vzdialenom repozitári na GitHube. Ak ich vidíte iba lokálne
  vo VS Code, zmeny ešte neboli úspešne odoslané pomocou <strong>push</strong>.</div